---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root

  vars:
    docker_compose_version: 1.27.4
  
  tasks:
    - name: Install the base required dependecies and suggest packages
      community.general.zypper:
        name: docker
        state: present
        disable_reccomends: no
